<?php
// config/design.php
return [
    'colors' => [
        '--bg'          => '#F5F2EE',
        '--bg2'         => '#EFEBE5',
        '--bg3'         => '#E8E2D9',
        '--bg4'         => '#DDD6CC',
        '--surface'     => '#FDFCFA',
        '--surface2'    => '#F7F4F0',
        '--border'      => '#E0D9D0',
        '--border2'     => '#CFC8BC',
        '--text'        => '#2C2824',
        '--text2'       => '#6B6158',
        '--text3'       => '#9B9088',
        '--accent'      => '#8B7355',
        '--accent-lt'   => '#F0EBE3',
        '--accent-dk'   => '#5C4A34',
        '--warm'        => '#C4956A',
        '--warm-lt'     => '#F5EDE4',
        '--warm-dk'     => '#8B5E3C',
        '--green'       => '#5C7A52',
        '--green-lt'    => '#EBF2E8',
        '--red'         => '#8B4444',
        '--red-lt'      => '#F5EDED',
        '--amber'       => '#8B7040',
        '--amber-lt'    => '#F5F0E8',
        '--blue'        => '#4A6B8A',
        '--blue-lt'     => '#EBF0F5',
    ],
    'fonts' => [
        '--font-sans'   => "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
        '--font-mono'   => "'JetBrains Mono', 'Fira Code', monospace",
        '--fs-xs'       => '11px',
        '--fs-sm'       => '12px',
        '--fs-base'     => '14px',
        '--fs-md'       => '15px',
        '--fs-lg'       => '17px',
        '--fs-xl'       => '20px',
        '--fs-2xl'      => '24px',
    ],
    'radii' => [
        '--radius'      => '10px',
        '--radius-lg'   => '14px',
        '--radius-xl'   => '20px',
        '--radius-pill' => '999px',
    ],
    'shadows' => [
        '--shadow-sm'   => '0 1px 4px rgba(0,0,0,.06)',
        '--shadow-md'   => '0 4px 16px rgba(0,0,0,.08)',
        '--shadow-lg'   => '0 8px 32px rgba(0,0,0,.12)',
    ],
];
